# YAML configuration file to set the mesh of the bicrystal indentation model
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

# Variables used to define the mesh of the bicrystal indentation model
w_sample: 4
h_sample: 4
len_sample: 6
ind_dist: 1
box_elm_nx: 7
box_elm_nz: 7
box_elm_ny1: 7
box_elm_ny2: 7
box_elm_ny3: 8
box_bias_x_mentat: 0.2
box_bias_z_mentat: 0.25
box_bias_y1_mentat: 0.3
box_bias_y2_mentat: 0
box_bias_y3_mentat: 0.3
box_bias_x_abaqus: 3
box_bias_z_abaqus: 3
box_bias_y1_abaqus: 3
box_bias_y2_abaqus: 1
box_bias_y3_abaqus: 3
mesh_quality_lvl: 1