# Be careful : only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!

# Matlab toolbox version
version_toolbox: '1.0'

# setting of opengl, e.g. 'software' or 'hardware' (optional)
matlab_opengl: software

# path for the documentation
doc_path: '..\doc\_build\html\index.html'