# Be careful : only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!

filenameGF2_BC: 'random_inputs'
filenameRB_BC: 'random_inputs'

#GB definition
GB_Number: 1
#GB_Trace_Angle: 0  #(in degree)
#GB_Inclination: 90 #(in degree)
    
#Grains definition (number and Euler angles in degree)
GrainA: 1
GrainB: 2
activeGrain: 1
Material_A: 'Ti'
Phase_A: 'hcp'
Material_B: 'Ti'
Phase_B: 'bcc'
eulerA: [205.8, 41.56, 46.47]
eulerB: [314.95, 39.86, 52.21]

#Specific slips for RBV calculation
SlipA_norm: [0, 0, 0, 1]
SlipA_dir: [2, -1, -1, 0]
SlipB_norm: [-2, 3, 1]
SlipB_dir: [1, 1, -1]
