# YAML configuration file to set material properties for CPFEM
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

# Material and Constitutive Laws
Phase2_material: Ti-beta
Phase2_elasticity: hooke
Phase2_plasticity: phenopowerlaw

# Outputs for the constitutive Laws
Phase2_output1: resistance_slip
Phase2_output2: shearrate_slip
Phase2_output3: resolvedstress_slip
Phase2_output4: accumulatedshear_slip
Phase2_output5: totalshear
Phase2_output6: resistance_twin
Phase2_output7: shearrate_twin
Phase2_output8: resolvedstress_twin
Phase2_output9: accumulatedshear_twin
Phase2_output10: totalvolfrac

# Crystal properties
Phase2_lattice_structure: bcc
Phase2_c11:    100e9
Phase2_c12:    100e9
Phase2_c44:    100e9

# Slip systems
Phase2_nslip: 12 0 # per family
Phase2_gdot0_slip: 0.001
Phase2_n_slip: 20
Phase2_tau0_slip: 500e6 0 0# per family
Phase2_tausat_slip: 1000e6 0# per family
Phase2_a_slip: 2.25

# Twin systems
Phase2_ntwin:  0 # per family
Phase2_gdot0_twin: 0.001
Phase2_n_twin: 20
Phase2_tau0_twin: 31e6 per family
Phase2_s_pr: 0 # push-up factor for slip saturation due to twinning
Phase2_twin_b: 0
Phase2_twin_c: 0
Phase2_twin_d: 0
Phase2_twin_e: 0
Phase2_h0_slipslip: 75.0e6
Phase2_h0_sliptwin: 0
Phase2_h0_twinslip: 0
Phase2_h0_twintwin: 0
Phase2_interaction_slipslip: '1 1 1.4 1.4 1.4 1.4'
Phase2_interaction_sliptwin: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'
Phase2_interaction_twinslip: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'
Phase2_interaction_twintwin: '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1'