# YAML configuration file to set the Matlab toolbox
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

# Matlab toolbox name
toolbox_name: 'STABiX'

# Matlab toolbox version
toolbox_version: '1.5'

# Month, Year
version_month: 'November'
version_year: '2014'

# Setting of opengl, e.g. 'software' or 'hardware' (optional)
matlab_opengl: software

# Source code repository
repository_url: 'http://github.com/stabix/stabix'

# Path for the documentation (html)
doc_path_root: 'http://stabix.readthedocs.org/en/latest/'

# Path for the documentation (pdf)
doc_path_pdf: 'https://media.readthedocs.org/pdf/stabix/latest/stabix.pdf'

# Path for bicrystal convention
doc_path_BXconv_png: '_images/Bicrystal_conventions.png'

# Path for bicrystal indentation mesh model
doc_path_BXind_png: '_images/BX_indentation_mesh_example.png'
    
# Path for single crystal indentation mesh model
doc_path_SXind_png: '_images/SX_indentation_mesh_example.png'