# YAML configuration file to set materials and samples
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

#Sample and Material definition
Sample_IDs: [Unknown, Sample_A, Sample_B]
Sample_ID: Unknown
Material_IDs: [Unknown, Material_A, Material_B]
Material_ID: Unknown

# path to your default data files (optional)
#default_grain_file_type2: MPIE_cpTi_grain_file_type2_2013.txt
#default_reconstructed_boundaries_file: MPIE_cpTi_reconstructed_boundaries_2013.txt