# YAML configuration file to set a specific single crystal
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

filenameGF2_BC: 'random_inputs'
filenameRB_BC: 'random_inputs'

#Grain definition (number and Euler angles in  degrees)
Material_A: 'Ti'
Phase_A: 'hcp'
GrainA: 1
activeGrain: 1
eulerA: [205.8, 41.56, 46.47]

#Specific slips
SlipA_norm: [0, 0, 0, 1]
SlipA_dir: [2, -1, -1, 0]