# YAML configuration file to set the mesh of the single crystal indentation model
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

# Variables used to define the mesh of the single crystal indentation model
r_center_frac: 0.25
box_xfrac: 0.3
box_zfrac: 0.3
D_sample: 8
h_sample: 4
sample_rep: 24
box_elm_nx: 10
box_elm_nz: 8
radial_divi: 10
box_bias_x: 0.1
box_bias_z: 0.2
box_bias_conv_x: 0.4