# YAML configuration file to set the mesh of the bicrystal indentation model
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

# Variables used to define the mesh of the bicrystal indentation model
coneAngle: 90 # Angle of cono-spherical indenter (in °)
tipRadius: 1 # Radius of cono-spherical indenter (in µm)
h_indent: 0.3 # Depth of indentation (in µm)
w_sample: 4
h_sample: 4
len_sample: 6
ind_dist: 1
box_elm_nx: 6
box_elm_nz: 6
box_elm_ny1: 6
box_elm_ny2: 7
box_elm_ny3: 6
box_bias_x: 0.2
box_bias_z: 0.25
box_bias_y1: 0.3
box_bias_y2: 0
box_bias_y3: 0.3
mesh_quality_lvl: 1