{TSLOIM_data_path_GF2: 'C:\Users\David\Documents\MWN2\data\Harsha_cpTi_3DXRD\2014-05-13_16h56m25s_TSL_DAMASK_files\2014-05-14_15h52m56s_TSL_files_93\',
  TSLOIM_data_path_RB: 'C:\Users\David\Documents\MWN2\data\Harsha_cpTi_3DXRD\2014-05-13_16h56m25s_TSL_DAMASK_files\2014-05-14_15h52m56s_TSL_files_93\'}
